### ISSUE TITLE
The problem of cycle time

### ISSUE THREAD

**Issue by zxcheergo** [Solla/Variable-LRA-Frequencies-on-DRV2605#1]
Why there are two peaks in the 1 second when the frequency is 1Hz?

**Comment by Solla** [comment]
The 1Hz is the frequency of the AC (alternating current).
As you can see, the directions of two peaks are opposite.

If you want to know how the LRA works, please refer to [How does a linear resonant actuator work.](https://e2e.ti.com/blogs_/b/analogwire/posts/how-does-a-linear-resonant-actuator-work)
