### ISSUE TITLE
How to connect DRV2605 with ESP32?

### ISSUE THREAD

**Issue by zxcheergo** [Solla/Variable-LRA-Frequencies-on-DRV2605#2]
When I have only one DRV2605L, how should I connect the SDA and SCL with the ESP32 board? I tried to use the SDA1(P0) and SCL1(P18), however, the LRA does not work.

**Comment by Solla** [comment]
The default IIC pins of ESP32 are GPIO22 & GPIO21. Please refer to [ESP32 Pinout Reference](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/).

If you want to use custom pins, you could find example code in the repo [DRV2605_Control_MultipleDRV2605.ino](https://github.com/Solla/Variable-LRA-Frequencies-on-DRV2605/blob/main/DRV2605_Control_MultipleDRV2605.ino), and the circuit diagram has been uploaded [here](https://github.com/Solla/Variable-LRA-Frequencies-on-DRV2605/raw/main/figures/Schematic.png). It can manipulate up to 20 DRV2605L simultaneously.

For more hardware-related issues, you can find resources at [https://esp32.com/](https://esp32.com/).

**Comment by zxcheergo** [comment]
Thank you so much for your help.
